### ISSUE TITLE
Checkboxes generated from GitHub Issue Forms and selected on form submission are not detected as selected

### ISSUE THREAD

**Issue by roni-frantchi** [issue-ops/parser#36]
Reason being is GitHub Issue Form generates the checkbox markdown with `- [X]`, as in, **uppercase** `X`, and the code only looks for lowercase: https://github.com/issue-ops/parser/blob/main/src/format.ts#L68-L70

**Comment by ncalteen** [comment]
Well that was silly of me to leave in there...I'm writing a fix now! Also apologies for waiting so long to reply to this one. I wasn't subscribed to get notifications for this repo!
