### ISSUE TITLE
Node.js 16 actions are deprecated

### ISSUE THREAD

**Issue by bmos** [issue-ops/parser#46]
When I use this, I get a deprecation error in the log:

> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: issue-ops/parser@v0. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

https://github.com/issue-ops/parser/blob/865037dc1f0eb6f2fd455c21ad76db0337ace8d0/action.yml#L30C3-L30C16

**Comment by ncalteen** [comment]
[v0.3.0](https://github.com/issue-ops/parser/releases/tag/v0.3.0) published with this update :)
