### ISSUE TITLE
[FEATURE REQUEST]: Turn into npm module

### ISSUE THREAD

**Issue by RyeToasts** [issue-ops/parser#79]
Hello @ncalteen,

Appreciate all awesome work you've done with this GitHub Action!

# Background

I utilize GitHub Issue Ops, but instead of running workflows based on new issues created, I use a GitHub App, via Webhook, to process the request. The content of those GitHub Issues are in JSON format, and you can imagine how often syntax issues occur without real time validation. I want to move over to GitHub Issue Forms, but haven't found a standardize NPM module that I feel will accomplish the parsing. This is where I found this action, and better yet, it's owned by GitHub and its sole purpose is to parse GitHub Issue Forms.

# Request:
Have this action be built as an NPM module to be used outside of GitHub Actions/Workflows.

**Comment by ncalteen** [comment]
Sorry for the radio silence on this! I 100% want to publish this as an npm module. Just working on getting some bandwidth :)
